from utils.config import LLM_MODEL

from model.LLM import LLMModel
from langchain.prompts import PromptTemplate

# system_prompt = '''You are a testing expert, and you will mutate input programs for testing static application security testing (SAST) tools. Your task is to construct variant programs that can trigger crash, false positive, or false negative bugs in Rust SAST tools, including: lockbud, rudra, mirchecker, semgrep, prusti, and MIRAI.'''
system_prompt = '''You are a testing expert, and you will mutate input programs for testing static application security testing (SAST) tools. Your task is to construct variant programs that can trigger crash, false positive, or false negative bugs in Rust tools, including: lockbud, rudra, mirchecker, semgrep, prusti, MIRAI for Rust and PMD, Infer, SpotBugs, SonarQube for Java.'''

llm_query = LLMModel(model_name=LLM_MODEL, system_message=system_prompt)

# # json format
# oracle1_prompt = '''The code of input program:
# ```rust
# {code}
# ```
# Its analysis report generated by {tool} is provided below:
# {document}
# The analysis report identifies the locations and descriptions of potential vulnerabilities in the input program. Please locate the code segments associated with these vulnerabilities, use program slicing to identify the relevant program elements and perform semantics-preserving transformations ensuring that the program behavior and the number of {vul_type} warnings in the analysis report generated by {tool} remain unchanged. For example, one such transformation could be replacing a library API with an equivalent API.. For example, replace a library API with an equivalent API. Generate more than {mutant_cnt} semantics-preserving mutant programs applying diverse transformations to mutate various elements, ensuring program diversity. Whenever possible, maximize the use of Rust language features such as closures, ownership, trait, and macros, to generate mutants through semantics-preserving transformations. If repeating a transformation, apply it at different locations and avoid merely renaming variables. Generate semantics-preserving mutants without fixing the {vul_type} vulnerability. As your goal is to find crash, FN, or FP bugs, I give you the checker document of {vul_type} in {tool}.
# {checker_doc}
# Understand the checker document and construct mutant programs to exploit them, triggering SAST bugs. You must only give me the source code of transformed programs and their code must be stored in json format with the key is with "mutant_index" ("index" means the number of generated test case) and the value is corresponding source code. You must not add comments and new line breaks in the response, I only need the pure code. A backslash must be added before double quotes to indicate an escape character.'''

# oracle1_prompt_template = '''The code of input program:
# ```rust
# {code}
# ```
# Its analysis report generated by {tool} is provided below:
# {document}
# The analysis report identifies the locations and descriptions of potential vulnerabilities in the input program. Please locate the code segments associated with these vulnerabilities, use program slicing to identify the relevant program elements and perform semantics-preserving transformations ensuring that the program behavior and the number of {vul_type} warnings in the analysis report generated by {tool} remain unchanged. For example, one such transformation could be replacing a library API with an equivalent API. Generate more than {mutant_cnt} mutants by applying various semantics-preserving transformations to ensure diversity. Whenever possible, maximize the use of Rust language features such as closures, ownership, and macros. As your goal is to find crash, FN, or FP bugs, I give you the checker document of {vul_type} in {tool} for understanding and construct mutants to trigger bugs:
# {checker_doc}
# You must only give me the source code of transformed programs, not add comments and new line breaks. Separate the adjacent mutants with a divider composed of three equal signs.'''

# few-shots
# oracle1_prompt = '''The code of input program:
# {input_program}
# Its analysis report generated by {tool} is: {report}. This report identifies the locations and types of potential bugs in the input program. Please locate the code segments associated with the bug, use program slicing to identify the relevant program elements and perform semantics-preserving transformations ensuring that the program behavior and the number of {bug_type} warnings in the analysis report remain unchanged. For example, two such transformations could be replacing a library API with an equivalent API and injecting dead code. Generate mutants by applying various semantics-preserving transformations to ensure diversity. Whenever possible, maximize the use of new programming language features. As your goal is to find crash, FN, or FP bugs, I give you the document of {bug_type} in {tool} for understanding and constructing mutants to trigger bugs: {bug_description} You must only give me the source code of transformed programs, not add comments and new line breaks. Separate the adjacent mutants with a divider composed of three equal signs.'''

# one-shot
oracle1_prompt = '''The code of input program:
{input_program}
Its analysis report generated by {tool} is: {report}. This report identifies the locations and types of potential bugs in the input program. Please locate the code segments associated with the bug, use program slicing to identify the relevant program elements and perform semantics-preserving transformations ensuring that the program behavior and the number of {bug_type} warnings in the analysis report remain unchanged. For example, replacing a library API with an equivalent one. Generate mutants by applying various semantics-preserving transformations to ensure diversity. Whenever possible, maximize the use of new programming language features. As your goal is to find crash, FN, or FP bugs, I give you the document of {bug_type} in {tool} for understanding and constructing mutants to trigger bugs: {bug_description} You must only give me the source code of transformed programs, not add comments and new line breaks. Separate the adjacent mutants with a divider composed of three equal signs.'''

oracle1_prompt_template = PromptTemplate(
    input_variables=["code", "tool", "document", "bug_type", "bug_description", "mutant_cnt"],
    template=oracle1_prompt
)

# oracle2_prompt = '''First, let me show you the description of {vul_type} vulnerability: {vul_document}.
# Then, here's a pair of code examples, including buggy and fixed programs.
# Buggy program:
# ```rust
# {buggy_program}
# ```
# Fixed_program:
# ```rust
# {fixed_program}
# ```
# Please learn fixing experience from the provided examples. Now, the input program is listed below:
# {input_program}
# Its analysis report generated by {tool} is:
# {report}
# The analysis report includes the location and description of {vul_type} vulnerabilities in the input program. Your task is selecting a {vul_type} vulnerability and use different approaches to fix it, then give me the fixed programs, eunsuring diversity. Make sure the repaired program preserves the original semantics and behavior. You must only give me the source code of transformed programs and their code must be stored in json format with the key is with "mutant_index" ("index" means the number of generated test case) and the value is corresponding source code. You must not add comments in the reply, I only need the code, and give me back the full program. In the generated code, a backslash should be added before double quotes to indicate an escape character.'''

# oracle2_prompt = '''First, let me show you the description of {vul_type} vulnerability: {vul_document}.
# Then, the following input program contains the {vul_type} vulnerability:
# ```rust
# {input_program}
# ```
# Its analysis report generated by {tool} is:
# {report}
# The report identifies the locations and descriptions of potential vulnerabilities in the input program. Your task is to locate a {vul_type} vulnerability listed in the report, fix it using diverse approaches, and provide the fixed programs, ensuring diversity, e.g., for a double lock vulnerability, you should try to release the first lock before acquiring the second lock. Provide as many distinct repaired programs as possible and ensure the repaired program maintains the original semantics and behavior. Your response must be in json format with the key is "mutant_index" ("index" means the number of generated test case) and the value is corresponding pure source code. You must not add comments and new line breaks in the response, I only need the pure code. A backslash must be added before double quotes to indicate an escape character.'''

# repair oracle
oracle2_prompt = '''First, let me show you the document of {bug_type} bug: {bug_document}.
Then, the following input program contains the {bug_type} bug:
{input_program}
Its analysis report of this program generated by {tool} is:
{report}
The report indicates the locations and descriptions of this type bug. Your task is to locate a {bug_type} bug via the report, fix it using diverse approaches, and provide the fixed programs, ensuring diversity, e.g., For a hardcoded crypto key bug, inject code that uses the hardcoded values in cryptographic APIs. Provide as many distinct repaired programs as possible. You must only give me the source code of transformed programs, not add comments and new line breaks. Separate the adjacent mutants with a divider composed of three equal signs.'''
# The report indicates the locations and descriptions of this type bug. Your task is to locate a {bug_type} bug via the report, fix it using diverse approaches, and provide the fixed programs, ensuring diversity, e.g., for a double lock bug, you should try to release the first lock before acquiring the second lock. Provide as many distinct repaired programs as possible. You must only give me the source code of transformed programs, not add comments and new line breaks. Separate the adjacent mutants with a divider composed of three equal signs.'''

oracle2_prompt_template = PromptTemplate(
    input_variables=["bug_type", "bug_document", "input_program", "tool", "report"],
    template=oracle2_prompt
)

# injection oracle
oracle3_prompt = '''Give you the description of {bug_type} bug: {bug_document} The following input program contains the {bug_type} bug:
{input_program}
Its analysis report generated by {tool} is:
{report}
The report identifies {bug_type} bugs in the input program. Based on the above information, understand the root cause of this bug. Your task is to inject new {bug_type} bugs while preserving existing code and ensuring diverse injection approaches, e.g., for a HardcodedCryptoKey bug, inject code that uses the hardcoded values in cryptographic APIs. Provide as many distinct, compilable, and vulnerability-injected programs as possible. You must only give me the source code of transformed programs without adding new comments and line breaks. Separate the adjacent mutants with a divider composed of three equal signs.'''
# The report identifies {bug_type} bugs in the input program. Based on the document and the input program, understand the principle and root cause of this bug. Your task is to inject new {bug_type} bugs while preserving existing code and ensuring diverse injection approaches. For a double lock bug, inject code that acquires the same lock twice without releasing the first. For a use-after-free bug, inject code that uses the released memory. Provide as many distinct, compilable, and vulnerability-injected programs as possible. You must only give me the source code of transformed programs without adding new comments and line breaks. Separate the adjacent mutants with a divider composed of three equal signs.'''

oracle3_prompt_template = PromptTemplate(
    input_variables=["bug_type", "tool", "bug_document", "input_program", "report"],
    template=oracle3_prompt)

fix_prompt = '''You provide me a test program in previous chat:
{generated_code}
However, it has the following compilation errors:
{compilation_error}
Please fix them and give me a correctly compliable program.
'''

fix_loop_prompt = '''You try to fix a test program previously:
{generated_code}
and the fixed program is:
{fixed_code}
However, it still has the following compilation errors:
{compilation_error}
'''